# Default initial positions for sentients1's ros2_control fake system

initial_positions:
  Linear_Joint: 1.0
  joint1: 1.5707
  joint2: 0
  joint3: -3.072
  joint4: 0
  joint5: 0
  joint6: -1.5707
  right_index_1_joint: 0
  right_little_1_joint: 0
  right_middle_1_joint: 0
  right_ring_1_joint: 0
  right_thumb_1_joint: 0
  right_thumb_2_joint: 0.52